import "dotenv/config";

export const $config = {
  NODE_ENV: process.env.NODE_ENV || "DEV",
  KEYCLOAK_ENDPOINT_BASE: process.env.KEYCLOAK_ENDPOINT_BASE,
  KEYCLOAK_CLIENT_ID: process.env.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_UUID: process.env.KEYCLOAK_CLIENT_UUID,
  KEYCLOAK_USER: process.env.KEYCLOAK_USER,
  KEYCLOAK_PASSWORD: process.env.KEYCLOAK_PASSWORD,
  KEYCLOAK_GRANT_TYPE: process.env.KEYCLOAK_GRANT_TYPE,
  KEYCLOAK_SECRET_KEY: process.env.KEYCLOAK_SECRET_KEY,
  KEYCLOAK_REALM: process.env.KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_USER_ID: process.env.KEYCLOAK_CLIENT_USER_ID!,
  PLAN_FREE_ID: process.env.PLAN_FREE_ID!,

  COOKIESESSIONSECRET: process.env.COOKIESESSIONSECRET,
  ORIGIN: process.env.ORIGIN,

  ORDER_IN_TRANSPORT_ID: process.env.ORDER_IN_TRANSPORT_ID!,
  ORDER_DELIVERED_ID: process.env.ORDER_DELIVERED_ID!,
  ORDER_CREATED_ID: process.env.ORDER_CREATED_ID!,

  URL_BASE: process.env.URL_BASE!,
  HEADER_TOKEN_PAYMENT: process.env.HEADER_TOKEN_PAYMENT!,

  URL_STORAGE_S3: process.env.URL_STORAGE_S3!,
  URL_STORAGE: process.env.URL_STORAGE!,
  HEADER_TOKEN_STORAGE: process.env.HEADER_TOKEN_STORAGE!,

  URL_FRONTEND: process.env.URL_FRONTEND!,

  SMTP_HOST: process.env.SMTP_HOST!,
  SMTP_PORT: process.env.SMTP_PORT!,
  SMTP_USER: process.env.SMTP_USER!,
  SMTP_USER_PASS: process.env.SMTP_USER_PASS!,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY!,
  URL_TRACKING: process.env.URL_TRACKING!,
  DOMAIN_COOKIES: process.env.DOMAIN_COOKIES || undefined,

  URL_VALIDATE_CTE: process.env.URL_VALIDATE_CTE!,

  BACKEND_TOKEN_CTE: process.env.BACKEND_TOKEN_CTE!,
  URL_BACKEND: process.env.URL_BACKEND!,
};
