version: '3.8'

services:
  app:
    build: .
    container_name: api-igreja
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"

  db:
    image: postgres:15-alpine
    container_name: db-igreja
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: